create table if not exists public.rsvp_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  guests integer not null check (guests >= 1 and guests <= 20),
  submitted_at timestamptz not null default timezone('utc', now())
);

create index if not exists rsvp_submissions_submitted_at_idx
  on public.rsvp_submissions (submitted_at desc);
