create table if not exists public.rsvp_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  guests integer not null check (guests >= 1 and guests <= 20),
  submitted_at timestamptz not null default timezone('utc', now())
);

create index if not exists rsvp_submissions_submitted_at_idx
  on public.rsvp_submissions (submitted_at desc);

-- Enable Row Level Security (required for anon key access)
alter table public.rsvp_submissions enable row level security;

-- Allow anyone to insert (public RSVP submission)
create policy "Allow public insert" on public.rsvp_submissions
  for insert with check (true);

-- Allow anyone to read (for rsvp-view page)
create policy "Allow public select" on public.rsvp_submissions
  for select using (true);
